apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: weather-app-ingress
  namespace: ns-weather-production
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  tls:
  - hosts:
    - weather2025.fr
    secretName: weather-app-tls
  rules:
  - host: weather2025.fr
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: weather-app-service
            port:
              number: 80

